DELETE http://localhost:3001/api/blogs/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOjEsImlhdCI6MTcyMTcyMTU1M30.uPiwRQYZ20oU8AhFrmhqSYFBp6gJp3GE2jFVUVZgzWw